### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by kawrou** [kawrou/recipeasy_fork#49]
## Description:
We should add some design elements and details about the website/web app to the home page so that a user can understand the purpose and features of the app without having to create an account.
We can add some GIF images to show the main features with a description next to them. 

## Task:
- [ ] Create GIF images for app features.
- [x] Create a new section on the home page for describing the app features.
- [ ] Add GIF images and text description of features in the new section.
- [x] Update website tab image.
